poweruse <- read.table("./household_power_consumption.txt", header=TRUE, sep=";")

poweruse$DateAsDate <- as.Date(poweruse$Date,"%d/%m/%Y")
poweruse$TimeAsTime <- strptime(poweruse$Time,"%H:%M:%S")
d2 <- subset(poweruse, DateAsDate=="2007-02-02")
d1 <- subset(poweruse, DateAsDate=="2007-02-01")
library("gtools")
library("gdata")
target <- combine(d1,d2)
target$srcDateAndTime <- paste(target$Date, target$Time)
target$DateAndTime <- strptime(target$srcDateAndTime,"%d/%m/%Y %H:%M:%S")

plot(target$DateAndTime, target$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
par(lheight=2)
legend("topright",  lty=1:1, col = c("grey","blue","red"), legend=c("Sub_metering_1 ","Sub_metering_2 ","Sub_metering_3 "))
par(col = 'grey')
lines(target$DateAndTime, target$Sub_metering_1)
par(col = 'red')
lines(target$DateAndTime, target$Sub_metering_2)
par(col = 'blue')
lines(target$DateAndTime, target$Sub_metering_3)
par(mar= c(3,2,2,1), ylog=TRUE)

dev.copy(png, file = "./plot3.png")
dev.off()
